---
abstract: 'Declarative parameters validation'
author:
  - 'Oleg Kostyuk <cub@cpan.org>'
build_requires:
  ClassOne: 0
  Data::Dumper: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validator-Declarative
requires:
  Email::Valid: 0
  Error: 0
  Module::Load: 0
  Readonly: 0
  Scalar::Util: 0
  strict: 0
  warnings: 0
version: 1.20130719.1300
